spring: 
  datasource: 
    password: 
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
  h2: 
    console: 
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers:
    - "localhost:9092"
    template:
      default-topic: USER_CREATED_TOPIC
