spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThiagoSousaSantana/restaurant
          search-paths:          - "config-properties/{application}/{profile}"